### ISSUE TITLE
Use EasyDB-generated UUIDs instead of Thomas-generated UUIDs

### ISSUE THREAD

**Issue by thomashaensli** [gtadigital/ProfileParser#28]
HI Matteo, 

as discussed, we should use the EasyDB-generated UUIDs. 

In the places XSL this is to be found here:  

https://github.com/gtadigital/ProfileParser/blob/4acc8498533c4da38f9b9e1dbe03fc540a7e9faa/Profiles/Place/livorno.xml#L94

**Comment by matteoLorenzini** [comment]
`<plIdentifier_uuid>833d0d54-f1ab-4108-8002-2e22b2cbb318</plIdentifier_uuid>`
