### ISSUE TITLE
Verify Place Parser

### ISSUE THREAD

**Issue by thomashaensli** [gtadigital/ProfileParser#39]
HI Mateo, can we later go over this sample export? 

A dopo, thanks, Thomas

https://github.com/gtadigital/ProfileParser/blob/eaec970a8eefb0eadec0403be9fa813756ff669d/Profiles/Place/fake-canton-annotated-example.xml#L1

**Comment by matteoLorenzini** [comment]
Ref. issues #44 #45 #46
