### ISSUE TITLE
Add identifier provider for SwissTopo-URI

### ISSUE THREAD

**Issue by thomashaensli** [gtadigital/ProfileParser#44]
can we add 

	 <plIdentifier_swisstopo_provider>
	 	<xsl:value-of select="pr:pl_nc_indentifier_swisstopo_provider/pr:generic_contributor/pr:_uuid"/>
	 </plIdentifier_swisstopo_provider>

after:

https://github.com/gtadigital/ProfileParser/blob/3a29dbfd3f83f8f891ecde182df7c29bfe01f9e0/Profiles/Place/Place.xsl#L46

**Comment by thomashaensli** [comment]
same goes for 

- pl_nc_indentifier_wikidata_provider
- pl_nc_indentifier_geonames_provider
- pl_nc_indentifier_gnd_provider
- pl_nc_indentifier_viaf_provider
- pl_nc_indentifier_dbpedia_provider
- pl_nc_indentifier_tgn_provider

**Comment by matteoLorenzini** [comment]
I have added also the identifier for the city of Zurich ```<plIdentifier_stzh_provider>```
