### ISSUE TITLE
add multiple parents

### ISSUE THREAD

**Issue by thomashaensli** [gtadigital/ProfileParser#45]
For non-political entities, namely physical entities (lakes, mountains) we need multiple parents. 

Can we add a path to 

```
   <_nested__pl__pl_ph_current_partof_place_manual>
      <pl__pl_ph_current_partof_place_manual>
        <pl_ph_current_partof_place_manual_place>
          <pl>
            <_uuid>9c0703fb-fc50-4aeb-99f0-15f89ea165a0</_uuid>
```

after the 'default' parent: 

https://github.com/gtadigital/ProfileParser/blob/169c46224bb82c18743db44543387428dbcdbd66/Profiles/Place/Place.xsl#L40

**Comment by thomashaensli** [comment]
HI Matteo, test record is updated, but export does not work the way it should. I'll try later, when the huge import is over and get back to you

**Comment by matteoLorenzini** [comment]
According to the last test record the Xpath is ``` /objects/pl/_nested__pl__pl_ph_current_partof_place_manual/pl__pl_ph_current_partof_place_manual/pl_ph_current_partof_place_manual_place/pl/_id``` with the ```_id``` insted of  ```_uuid``

**Comment by thomashaensli** [comment]
That si correct, only that the export shortens the xml at that point (Line 100, no _uuid). What shall we do? Spit for the moment?
