### ISSUE TITLE
Do we need this?

### ISSUE THREAD

**Issue by matteoLorenzini** [gtadigital/ProfileParser#47]
https://github.com/gtadigital/ProfileParser/blob/e0e2713b94f0fd0e8b1950bc2e1c394e0b0dc3e3/Profiles/Place/target_new_v2.xml#L5

This definition refers directly to the use case issue #38 . Do we need the definition of the name_literal or is enough to have the name in 4 languages?

**Comment by thomashaensli** [comment]
We should go with  <plIdentifier_name_literal> and drop the 4 language scheme (that's EasyDB internally and limited to 4 languages)
