### ISSUE TITLE
new export data for ETL available (v3)

### ISSUE THREAD

**Issue by thomashaensli** [gtadigital/ProfileParser#50]
HI Matteo, 

here are the new place export data from EDB for ETL: 
https://shared.ethz.ch/s/4WNcfQ3YQJ5QD8y

Note: with raising complexity, EDB has troubles to dump all in one file. Thus, here you find batches of 100 records (7 folder à 100 xml à 100 records = approx 70k records). Can you work with this? 

(I'll  keep trying a one-piece dump meawhile)

Th.

**Comment by thomashaensli** [comment]
PS needless to write, this dump reflects the fixed typos in #49

**Comment by thomashaensli** [comment]
Hoi Matteo, 

all-in-one export worked this time. Can you check it against the .XSL? 

Thanks, Th. 

BTW: new export record in line numbers... 59Mio! Technically, that's the new definition of verboseness...

**Comment by matteoLorenzini** [comment]
New dump available [here](https://nextcloud.ethz.ch/apps/files?dir=/lorenzini/places_export/v3-20200630-batches-of-10000&fileid=53107743)

**Comment by matteoLorenzini** [comment]
@thomashaensli [here](https://nextcloud.ethz.ch/apps/files/?dir=/lorenzini/places_export/v3-20200630-batches-of-10000&fileid=53107743) the new dump
